export const dataDiv = [
  {
    dealer_code: "M5300",
    division: "Division1",
    dealership_name: "Dealership One",
    phone: 1234567890,
    email: "email1@example.com",
    alt_email: "alt1@example.com",
    dlr_status: "N",
    location: "Location1",
    dlr_gstin: "GSTIN123456",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-01-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-01-01",
    update_id: 2,
    update_date: "2024-01-01",
  },
  {
    dealer_code: "M5400",
    division: "Division2",
    dealership_name: "Dealership Two",
    phone: "0987654321",
    email: "email2@example.com",
    alt_email: "alt2@example.com",
    dlr_status: "Y",
    location: "Location2",
    dlr_gstin: "GSTIN654321",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-02-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-02-01",
    update_id: 2,
    update_date: "2024-02-01",
  },
  {
    dealer_code: "M5500",
    division: "Division3",
    dealership_name: "Dealership Three",
    phone: 2345678901,
    email: "email3@example.com",
    alt_email: "alt3@example.com",
    dlr_status: "N",
    location: "Location3",
    dlr_gstin: "GSTIN345678",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-03-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-03-01",
    update_id: 2,
    update_date: "2024-03-01",
  },
  {
    dealer_code: "M5600",
    division: "Division4",
    dealership_name: "Dealership Four",
    phone: 3456789012,
    email: "email4@example.com",
    alt_email: "alt4@example.com",
    dlr_status: "Y",
    location: "Location4",
    dlr_gstin: "GSTIN456789",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-04-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-04-01",
    update_id: 2,
    update_date: "2024-04-01",
  },
  {
    dealer_code: "M5700",
    division: "Division5",
    dealership_name: "Dealership Five",
    phone: 4567890123,
    email: "email5@example.com",
    alt_email: "alt5@example.com",
    dlr_status: "N",
    location: "Location5",
    dlr_gstin: "GSTIN567890",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-05-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-05-01",
    update_id: 2,
    update_date: "2024-05-01",
  },
  {
    dealer_code: "M5800",
    division: "Division6",
    dealership_name: "Dealership Six",
    phone: 5678901234,
    email: "email6@example.com",
    alt_email: "alt6@example.com",
    dlr_status: "Y",
    location: "Location6",
    dlr_gstin: "GSTIN678901",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-06-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-06-01",
    update_id: 2,
    update_date: "2024-06-01",
  },
  {
    dealer_code: "M5900",
    division: "Division7",
    dealership_name: "Dealership Seven",
    phone: 6789012345,
    email: "email7@example.com",
    alt_email: "alt7@example.com",
    dlr_status: "N",
    location: "Location7",
    dlr_gstin: "GSTIN789012",
    dlr_active: "Y",
    dlr_appoint_dt: "2023-07-01",
    dlr_inoperative: "N",
    dlr_inoperative_dt: "NULL",
    dlr_cess_dt: "NULL",
    create_id: 1,
    create_date: "2023-07-01",
    update_id: 2,
    update_date: "2024-07-01",
  },
];
